### ISSUE TITLE
Configurable modifier signs

### ISSUE THREAD

**Issue by pickled-plugins** [ingdir/jquery-bemhelpers#3]
I am using a sign convention that signals modifier classes by ``--`` instead of ``_``, as per [this article](https://css-tricks.com/bem-101/). This plug-in would be helpful for me if I could set this as a configuration option.

**Comment by ingdir** [comment]
2.2.1 now has support for custom BEM syntax. Set it with the `$.BEMsyntax()` method (see readme). If you don't use key/value modifiers, for `modKeyVal` just provide a value you'd never use.

**Comment by pickled-plugins** [comment]
Eexcellent, thank you!
